paths:
  excel_hypoxia: "data/DataBase_Futbol_2025v.xlsx"
  gps_csv: "data/export_15-09-25.csv"
  positions_csv: "data/positions.csv"
outputs:
  figures_dir: "outputs/figures"
  tables_dir: "outputs/tables"

analysis:
  use_blocks_for_ols: [1, 2, 3, 4]   # change to [1..6] if needed
  mixed_blocks: [1, 2, 3, 4, 5, 6]   # mixed-effects window
  min_sessions_for_ols: 4
  min_sessions_for_mixed: 6
  anonymize: false
